In [4]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
ds = pd.read_excel('https://raw.githubusercontent.com/krishnaik06/Flight-Price-Prediction1/main/flight_price.xlsx')

In [6]:
ds

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [7]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [8]:
ds['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [9]:
ds['Date_of_Journey'].unique()

array(['24/03/2019', '1/05/2019', '9/06/2019', '12/05/2019', '01/03/2019',
       '24/06/2019', '12/03/2019', '27/05/2019', '1/06/2019',
       '18/04/2019', '9/05/2019', '24/04/2019', '3/03/2019', '15/04/2019',
       '12/06/2019', '6/03/2019', '21/03/2019', '3/04/2019', '6/05/2019',
       '15/05/2019', '18/06/2019', '15/06/2019', '6/04/2019',
       '18/05/2019', '27/06/2019', '21/05/2019', '06/03/2019',
       '3/06/2019', '15/03/2019', '3/05/2019', '9/03/2019', '6/06/2019',
       '24/05/2019', '09/03/2019', '1/04/2019', '21/04/2019',
       '21/06/2019', '27/03/2019', '18/03/2019', '12/04/2019',
       '9/04/2019', '1/03/2019', '03/03/2019', '27/04/2019'], dtype=object)

In [10]:
pd.to_datetime(ds['Date_of_Journey'],infer_datetime_format=True)

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[ns]

In [11]:
ds['Date_of_Journey'] = pd.to_datetime(ds['Date_of_Journey'],infer_datetime_format=True)

In [12]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  datetime64[ns]
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 918.2+ KB

In [13]:
ds['Day'] = ds['Date_of_Journey'].dt.day
ds['Month'] = ds['Date_of_Journey'].dt.month
ds['Year'] = ds['Date_of_Journey'].dt.year
ds.drop('Date_of_Journey',axis=1,inplace=True)

In [14]:
ds

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [15]:
ds['Dep_Time'].unique()

array(['22:20', '05:50', '09:25', '18:05', '16:50', '09:00', '18:55',
       '08:00', '08:55', '11:25', '09:45', '20:20', '11:40', '21:10',
       '17:15', '16:40', '08:45', '14:00', '20:15', '16:00', '14:10',
       '22:00', '04:00', '21:25', '21:50', '07:00', '07:05', '09:50',
       '14:35', '10:35', '15:05', '14:15', '06:45', '20:55', '11:10',
       '05:45', '19:00', '23:05', '11:00', '09:35', '21:15', '23:55',
       '19:45', '08:50', '15:40', '06:05', '15:00', '13:55', '05:55',
       '13:20', '05:05', '06:25', '17:30', '08:20', '19:55', '06:30',
       '14:05', '02:00', '09:40', '08:25', '20:25', '13:15', '02:15',
       '16:55', '20:45', '05:15', '19:50', '20:00', '06:10', '19:30',
       '04:45', '12:55', '18:15', '17:20', '15:25', '23:00', '12:00',
       '14:45', '11:50', '11:30', '14:40', '19:10', '06:00', '23:30',
       '07:35', '13:05', '12:30', '15:10', '12:50', '18:25', '16:30',
       '00:40', '06:50', '13:00', '19:15', '01:30', '17:00', '10:00',
       '19:35', '15:30', '12:10', '16:10', '20:35', '22:25', '21:05',
       '05:35', '05:10', '06:40', '15:15', '00:30', '08:30', '07:10',
       '05:30', '14:25', '05:25', '10:20', '17:45', '13:10', '22:10',
       '04:55', '17:50', '21:20', '06:20', '15:55', '20:30', '17:25',
       '09:30', '07:30', '02:35', '10:55', '17:10', '09:10', '18:45',
       '15:20', '22:50', '14:55', '14:20', '13:25', '22:15', '11:05',
       '16:15', '20:10', '06:55', '19:05', '07:55', '07:45', '10:10',
       '08:15', '11:35', '21:00', '17:55', '16:45', '18:20', '03:50',
       '08:35', '19:20', '20:05', '17:40', '04:40', '17:35', '09:55',
       '05:00', '18:00', '02:55', '20:40', '22:55', '22:40', '21:30',
       '08:10', '17:05', '07:25', '15:45', '09:15', '15:50', '11:45',
       '22:05', '18:35', '00:25', '19:40', '20:50', '22:45', '10:30',
       '23:25', '11:55', '10:45', '11:15', '12:20', '14:30', '07:15',
       '01:35', '18:40', '09:20', '21:55', '13:50', '01:40', '00:20',
       '04:15', '13:45', '18:30', '06:15', '02:05', '12:15', '13:30',
       '06:35', '10:05', '08:40', '03:05', '21:35', '16:35', '02:30',
       '16:25', '05:40', '15:35', '13:40', '07:20', '04:50', '12:45',
       '10:25', '12:05', '11:20', '21:40', '03:00'], dtype=object)

In [16]:
# ds['Dep_Time'].str.split(':')
ds['Dep_Hr'] = ds['Dep_Time'].str.split(':').str[0].astype(int)
ds['Dep_Se'] = ds['Dep_Time'].str.split(':').str[1].astype(int)
ds.drop('Dep_Time',axis=1,inplace=True)

In [17]:
ds

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hr,Dep_Se
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,22:25,2h 30m,non-stop,No info,4107,9,4,2019,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,23:20,2h 35m,non-stop,No info,4145,27,4,2019,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,11:20,3h,non-stop,No info,7229,27,4,2019,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,14:10,2h 40m,non-stop,No info,12648,1,3,2019,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,19:15,8h 20m,2 stops,No info,11753,9,5,2019,10,55

In [18]:
ds['Arrival_Time'].unique()

array(['01:10 22 Mar', '13:15', '04:25 10 Jun', ..., '06:50 10 Mar',
       '00:05 19 Mar', '21:20 13 Mar'], dtype=object)

In [19]:
ds['Arr_Hr'] = ds['Arrival_Time'].apply(lambda x: x.split(' ')[0].split(':')[0]).astype(int)
ds['Arr_Min'] = ds['Arrival_Time'].apply(lambda x: x.split(' ')[0].split(':')[1]).astype(int)
ds.drop('Arrival_Time',axis=1,inplace=True)

In [20]:
ds
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Day              10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Dep_Hr           10683 non-null  int64
 12  Dep_Se           10683 non-null  int64
 13  Arr_Hr           10683 non-null  int64
 14  Arr_Min          10683 non-null  int64
dtypes: int64(8), object(7)
memory usage: 1.2+ MB

In [21]:
ds['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [22]:
ds['Total_Stops'].value_counts()

1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: Total_Stops, dtype: int64

In [23]:
ds['Total_Stops'] = ds['Total_Stops'].map({'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,'non-stop':0,'nan':1})

In [24]:
ds

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hr,Dep_Se,Arr_Hr,Arr_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2.0,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1.0,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1.0,No info,13302,1,3,2019,16,50,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,0.0,No info,4107,9,4,2019,19,55,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,0.0,No info,4145,27,4,2019,20,45,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,0.0,No info,7229,27,4,2019,8,20,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,0.0,No info,12648,1,3,2019,11,30,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2.0,No info,11753,9,5,2019,10,55,19,15

In [25]:
ds['Duration'].unique()

array(['2h 50m', '7h 25m', '19h', '5h 25m', '4h 45m', '2h 25m', '15h 30m',
       '21h 5m', '25h 30m', '7h 50m', '13h 15m', '2h 35m', '2h 15m',
       '12h 10m', '26h 35m', '4h 30m', '22h 35m', '23h', '20h 35m',
       '5h 10m', '15h 20m', '2h 55m', '13h 20m', '15h 10m', '5h 45m',
       '5h 55m', '13h 25m', '22h', '5h 30m', '10h 25m', '5h 15m',
       '2h 30m', '6h 15m', '11h 55m', '11h 5m', '8h 30m', '22h 5m',
       '2h 45m', '12h', '16h 5m', '19h 55m', '3h 15m', '25h 20m', '3h',
       '16h 15m', '15h 5m', '6h 30m', '25h 5m', '12h 25m', '27h 20m',
       '10h 15m', '10h 30m', '1h 30m', '1h 25m', '26h 30m', '7h 20m',
       '13h 30m', '5h', '19h 5m', '14h 50m', '2h 40m', '22h 10m',
       '9h 35m', '10h', '21h 20m', '18h 45m', '12h 20m', '18h', '9h 15m',
       '17h 30m', '16h 35m', '12h 15m', '7h 30m', '24h', '8h 55m',
       '7h 10m', '14h 30m', '30h 20m', '15h', '12h 45m', '10h 10m',
       '15h 25m', '14h 5m', '20h 15m', '23h 10m', '18h 10m', '16h',
       '2h 20m', '8h', '16h 55m', '3h 10m', '14h', '23h 50m', '21h 40m',
       '21h 15m', '10h 50m', '8h 15m', '8h 35m', '11h 50m', '27h 35m',
       '8h 25m', '20h 55m', '4h 50m', '8h 10m', '24h 25m', '23h 35m',
       '25h 45m', '26h 10m', '28h 50m', '25h 15m', '9h 20m', '9h 10m',
       '3h 5m', '11h 30m', '9h 30m', '17h 35m', '5h 5m', '25h 50m', '20h',
       '13h', '18h 25m', '24h 10m', '4h 55m', '25h 35m', '6h 20m',
       '18h 40m', '19h 25m', '29h 20m', '9h 5m', '10h 45m', '11h 40m',
       '22h 55m', '37h 25m', '25h 40m', '13h 55m', '8h 40m', '23h 30m',
       '12h 35m', '24h 15m', '1h 20m', '11h', '11h 15m', '14h 35m',
       '12h 55m', '9h', '7h 40m', '11h 45m', '24h 55m', '17h 5m',
       '29h 55m', '22h 15m', '14h 40m', '7h 15m', '20h 10m', '20h 45m',
       '27h', '24h 30m', '20h 25m', '5h 35m', '14h 45m', '5h 40m',
       '4h 5m', '15h 55m', '7h 45m', '28h 20m', '4h 20m', '3h 40m',
       '8h 50m', '23h 45m', '24h 45m', '21h 35m', '8h 5m', '6h 25m',
       '15h 50m', '26h 25m', '24h 50m', '26h', '23h 5m', '7h 55m',
       '26h 20m', '23h 15m', '5h 20m', '4h', '9h 45m', '8h 20m',
       '17h 25m', '7h 5m', '34h 5m', '6h 5m', '5h 50m', '7h', '4h 25m',
       '13h 45m', '19h 15m', '22h 30m', '16h 25m', '13h 50m', '27h 5m',
       '28h 10m', '4h 40m', '15h 40m', '4h 35m', '18h 30m', '38h 15m',
       '6h 35m', '12h 30m', '11h 20m', '7h 35m', '29h 35m', '26h 55m',
       '23h 40m', '12h 50m', '9h 50m', '21h 55m', '10h 55m', '21h 10m',
       '20h 40m', '30h', '13h 10m', '8h 45m', '6h 10m', '17h 45m',
       '21h 45m', '3h 55m', '17h 20m', '30h 30m', '21h 25m', '12h 40m',
       '24h 35m', '19h 10m', '22h 40m', '14h 55m', '21h', '6h 45m',
       '28h 40m', '9h 40m', '16h 40m', '16h 20m', '16h 45m', '1h 15m',
       '6h 55m', '11h 25m', '14h 20m', '12h 5m', '24h 5m', '28h 15m',
       '17h 50m', '20h 20m', '28h 5m', '10h 20m', '14h 15m', '35h 15m',
       '35h 35m', '26h 40m', '28h', '14h 25m', '13h 5m', '37h 20m',
       '36h 10m', '25h 55m', '35h 5m', '19h 45m', '27h 55m', '47h',
       '10h 35m', '1h 35m', '16h 10m', '38h 20m', '6h', '16h 50m',
       '14h 10m', '23h 20m', '17h 40m', '11h 35m', '18h 20m', '6h 40m',
       '30h 55m', '24h 40m', '29h 50m', '28h 25m', '17h 15m', '22h 45m',
       '25h 25m', '21h 50m', '33h 15m', '30h 15m', '3h 35m', '27h 40m',
       '30h 25m', '18h 50m', '27h 45m', '15h 15m', '10h 40m', '26h 15m',
       '36h 25m', '26h 50m', '15h 45m', '19h 40m', '22h 25m', '19h 35m',
       '25h', '26h 45m', '38h', '4h 15m', '25h 10m', '18h 15m', '6h 50m',
       '23h 55m', '17h 55m', '23h 25m', '17h 10m', '24h 20m', '28h 30m',
       '27h 10m', '19h 20m', '15h 35m', '9h 25m', '21h 30m', '34h 25m',
       '18h 35m', '29h 40m', '26h 5m', '29h 5m', '27h 25m', '16h 30m',
       '11h 10m', '28h 55m', '29h 10m', '34h', '30h 40m', '30h 45m',
       '32h 55m', '10h 5m', '35h 20m', '32h 5m', '31h 40m', '19h 50m',
       '33h 45m', '30h 10m', '13h 40m', '19h 30m', '31h 30m', '34h 30m',
       '27h 50m', '38h 35m', '42h 5m', '4h 10m', '39h 5m', '3h 50m', '5m',
       '32h 30m', '31h 55m', '33h 20m', '27h 30m', '18h 55m', '9h 55m',
       '41h 20m', '20h 5m', '31h 50m', '42h 45m', '3h 25m', '37h 10m',
       '29h 30m', '32h 20m', '20h 50m', '40h 20m', '13h 35m', '47h 40m'],
      dtype=object)

In [26]:
[int(x.split(' ')[0][0:-1]) if x.split(' ')[0][-1] =='m' else int(x.split(' ')[0][0:-1])*60 + int(x.split(' ')[0][0:-1])  for x in ['2h 50m	','7h 5m', '5h', '11m']]

[122, 427, 305, 11]

In [27]:
ds[ds['Duration']=='5m']
ds.drop(6474, axis=0,inplace=True)

In [28]:
ds['DurHr'] = ds['Duration'].apply(lambda x:x.split(' ')[0][0:-1]).astype(int)

In [29]:
ds['DurMin'] = ds['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [30]:
ds['DurMin'] = ds['DurMin'].fillna(0).astype(int)

In [31]:
ds
ds.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10682 entries, 0 to 10682
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10681 non-null  object
 4   Duration         10682 non-null  object
 5   Total_Stops      10681 non-null  float64
 6   Additional_Info  10682 non-null  object
 7   Price            10682 non-null  int64
 8   Day              10682 non-null  int64
 9   Month            10682 non-null  int64
 10  Year             10682 non-null  int64
 11  Dep_Hr           10682 non-null  int64
 12  Dep_Se           10682 non-null  int64
 13  Arr_Hr           10682 non-null  int64
 14  Arr_Min          10682 non-null  int64
 15  DurHr            10682 non-null  int64
 16  DurMin           10682 non-null  int64
dtypes: float64(1), int64(10), object(6)
memory usage: 1.5+ MB

In [32]:
ds.drop('Duration', axis=1, inplace=True)

In [33]:
ds

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Day,Month,Year,Dep_Hr,Dep_Se,Arr_Hr,Arr_Min,DurHr,DurMin
0,IndiGo,Banglore,New Delhi,BLR → DEL,0.0,No info,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2.0,No info,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2.0,No info,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1.0,No info,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1.0,No info,13302,1,3,2019,16,50,21,35,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0.0,No info,4107,9,4,2019,19,55,22,25,2,30
10679,Air India,Kolkata,Banglore,CCU → BLR,0.0,No info,4145,27,4,2019,20,45,23,20,2,35
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0.0,No info,7229,27,4,2019,8,20,11,20,3,0
10681,Vistara,Banglore,New Delhi,BLR → DEL,0.0,No info,12648,1,3,2019,11,30,14,10,2,40
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2.0,No info,11753,9,5,2019,10,55,19,15,8,20

In [34]:
ds.groupby('Airline')['Price'].mean().sort_values()

Airline
Trujet                                4140.000000
SpiceJet                              4338.284841
Air Asia                              5590.260188
IndiGo                                5673.682903
GoAir                                 5861.056701
Vistara                               7796.348643
Vistara Premium economy               8962.333333
Air India                             9606.804112
Multiple carriers                    10902.678094
Multiple carriers Premium economy    11418.846154
Jet Airways                          11643.923357
Jet Airways Business                 58358.666667
Name: Price, dtype: float64

In [36]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [39]:
ohe.fit_transform(ds[['Airline']]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [41]:
pd.DataFrame(ohe.fit_transform(ds[['Airline']]).toarray(), columns = ohe.get_feature_names_out())

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,Airline_Vistara,Airline_Vistara Premium economy
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10677,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10678,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10679,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0